 $('.nav-tabs').addClass('fl').css('width','100%');$('a[href="https://jawalhost.com/"]').removeAttr('href');$(`<link href="https://fonts.googleapis.com/css?family=Aref+Ruqaa|El+Messiri" rel="stylesheet"><link rel="stylesheet" href="shoq.wapka.co/rak"><style>textarea.fl.filw.corner.tbox {border-radius: 10px;padding-left: 5px;border: 2px solid #adadad;margin-top: 2px;}.label.tc.border.btn.fl, .label.tc.border.btn.fl {border: 2px solid #316C7D;font-family: 'El Messiri',FontAwesome;border-radius: 3px;}</style>`).insertBefore('body');$('.hand.nosel.fl.uzr.border').css({'margin': '0px',borderRight: '3px solid #316C7D',borderLeft: '3px solid #316C7D',borderTop: '1px solid #A89791',borderBottom: '1px solid #e2e1e1',borderRadius: '3px'});$(`<link rel='stylesheet' id='themename_style-css'  href='https://shoq.wapka.co/rak' type='text/css' media='all' /></style>`).insertBefore('body');$(`<style> img.fitimg.fl.u-pic {border-radius:7px;box-shadow:0 0 1px 0 rgb(0 0 0 / 43%);border:1px dashed #000} </style>`).insertBefore('body');

$(`<img src=""class="fr" style="width:100%;margin-top: 1px;"> <a href="" style="width:90px;margin:2px;" class="fl mini fa fa-phone btn btn-primary"> الاداره</a> <a href="#" style="width:90px;margin:2px;" class="fl mini fa fa-heartbeat btn btn-primary">التطبيق </a> <a href="" style="width:93px;margin:2px;" class="fl mini fa fa-star btn btn-primary"> ميز نفسك </a> <a href="#" style="width:94px;margin:2px;" class="fl mini fa fa-graduation-cap btn btn-primary"> القوانين</a> `).insertBefore('.nav-tabs'); $(`<center><div><div width="99.5%" style="background-image:url;color: #160701;border-radius: 10px 5px 5px10px;border-bottom: 2px solid #ffffff;border-top: 2px solid#ffffff;padding-bottom: 2px!important;" > <font style="background-color: #fff;border-radius: 15px 15px 15px 15px;font-family: 'jazeera',FontAwesome;padding: 2px 10px 2px 10px;margin: 7px 10px 7px 10px;" color="#7A7A7A" > اهلا وسهلا بكم في دردشه تعب قلوب الصوتي</font></div></div><center>`).insertBefore('#d2'); $(".label-primary").css("border-radius","1px 1px 1px 1px"); $(`<style> img.fitimg.fl.u-pic {border-radius:7px;box-shadow:0 0 1px 0 rgb(0 0 0 / 43%);border:1px dashed #000} </style>`).insertBefore('body'); 


$(`<style> .btn.minix.btn-primary.fa.fa-reply.fr{background:#ffffff00!important;color:#CBCEE3;border:0;FONT-WEIGHT:500!important}.btn.minix.btn-primary.fa.fa-times.fr{background:#ffffff00!important;color:red;border:0;FONT-WEIGHT:500!important}.btn-danger{background:red!important;border-radius:2px!important}.fl.ustat{height:9px!important;width:9px!important;border-radius:20px 0 0 50px!important}.border,div#tlogins{box-shadow:inset 1px 1px 1px 0 #9494946b,0 0 2px #9494949e!important}.border{border:#e8e8e8 solid 1px}.light{background:repeating-linear-gradient(45deg,rgba(255,255,255,.8),rgb(255,255,255) 100px,#ffffffb0 0,#fff6f699 200px),repeating-linear-gradient(-45deg,rgba(255,255,255,.5),rgba(255,255,255,.93) 100px,#b3adadd1 0,#C4C4C4 200px)!important}.pmsgc{outline:1px dashed #b3adad;outline-offset:-5px;background-size:auto;background-position:100% 0%;background-color:#C4C4C460!important}.ae.fa.label.label-primary.fa-user{border-left:4px solid #c5c5c5;}.ae.label.label-primary.fa.fa-bolt,.ae.fa.label.label-primary.fa-microphone{    display: none!important;} </style>`).insertBefore('body');
$("[data-target=#wall]").attr('title','ممبدعين تعب قلوب الصوتي')
$("[data-target=#settings]").attr('title','اعدادات تعب قلوب')
$("[data-target=#rooms]").attr('title',' رومات تعب قلوب الصوتي')
$("[data-target=#chats]").attr('title',' المحادثات الخاصه تعب قلوب')
$("[data-target=#users]").attr('title','المتواجدين بدردشه تعب قلوب')
$('.fl.ustat')
    .css('width', '3px'), $('.fa.fa-user-plus')
    .html(`تسجيل العضويات`), document.getElementById('u1')
    .placeholder = ' حط اسمك ي حلو❤️ ', 
document.getElementById('pass1')
  .placeholder = 'حطلي باسوردك هنا 🗝️', document.getElementById('u2')
    .placeholder = 'فخأمه طلتك تنورنا 🥰', document.getElementById('pass2')
    .placeholder = ' باسوردك ولا تنساه ي جميل 😘 ', document.getElementById('u3')
    .placeholder = 'اكتب اسمك ولازم تحفظه ❤️ ';
    $("[data-target=#wall]").attr('title',' مبدعين حائط تعب قلوب') ;


$(`<marquee direction="right" width="65%" direction="right" style="margin-bottom: -7px;font-family: 'jann', sans-serif; height: 20px;" onmouseover="this.stop()" onmouseout="this.start()" scrolldelay="0" scrollamount="5"><font style="background-color: #â€ڈB7B6BA;border-radius: 15px 15px 15px 15px;font-family: 'jann',FontAwesome;padding: 2px 10px 2px 10px;margin: 7px 10px 7px 10px;">اهلا وسهلا بكم في دردشه تعب قلوب الصوتي نتمنى لكم قضاء امتع الاوقات - www.te3bchat.com </marquee></font></b></td>`).insertBefore('span.s1.fa.fa-user.label.badgex.label-as-badge.label-success');
